INSERT INTO roles (type)
SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT * FROM roles WHERE type = 'ROLE_USER');
INSERT INTO roles (type)
SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT * FROM roles WHERE type = 'ROLE_ADMIN');